# Generated by Django 5.0.4 on 2024-07-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('requesting', 'Requesting')], default='available', max_length=10)),
                ('plug', models.BooleanField(blank=True, null=True)),
                ('backseat', models.BooleanField(blank=True, null=True)),
                ('seat_start_time', models.DateTimeField(blank=True, null=True)),
                ('seat_use_time', models.DurationField(blank=True, null=True)),
                ('seats_no', models.IntegerField(blank=True, null=True)),
                ('seats_count', models.IntegerField(blank=True, null=True)),
                ('empty_seats', models.IntegerField(blank=True, null=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='accounts.cafe')),
            ],
            options={
                'db_table': 'seats',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('user_id', models.IntegerField(default=1)),
                ('seats_no', models.IntegerField(blank=True, null=True)),
                ('reservation_time', models.DateTimeField(auto_now_add=True)),
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cafe')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.seat')),
            ],
        ),
    ]
